# coding=utf-8# -*- coding: utf-8 -*-
# # SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
# #
# # SPDX-License-Identifier: AGPL-3.0-or-later
#
# # -*- coding: utf-8 -*-
exclude: "^LICENSES"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ["--maxkb=2000"]

# Run ruff to lint and format
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.0
  hooks:
    # Run the linter.
  - id: ruff
    types_or: [python]
    args: [--fix]
    # Run the formatter.
  - id: ruff-format
    types_or: [python]

  # Find common spelling mistakes in comments and docstrings
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ['--ignore-regex="(\b[A-Z]+\b)"', '--ignore-words-list=fom,appartment,bage,ore,setis,tabacco,berfore,vor,pris,WEGE,Wege,Eletricity'] # Ignore capital case words, e.g. country codes
    types_or: [python, rst, markdown]
    files: ^(analysis/scripts)/

  # YAML formatting
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    exclude: pinned\.yaml$
    args: [--autofix, --indent, "2", --preserve-quotes]

  # Format Snakemake rule / workflow files
- repo: https://github.com/snakemake/snakefmt
  rev: v0.11.0
  hooks:
  - id: snakefmt
