# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0


# Options specific to geothermal project
US:
  # Config options to scale demand to future years based on NREL EFS study
  demand_projection:
    planning_horizon: 2035 # Year to be considered for future demand projections between 2030-2050
    scenario: "Reference" # Choices - [Reference, Moderate, High]
    thermal_scenario: "reference case"

run:
  name: "US_2035_inflexible_EGS" # use this to keep track of runs with different settings
  sector_name: "US_2035_inflexible_EGS"
  shared_cutouts: true  # set to true to share the default cutout(s) across runs
                        # Note: value false requires build_cutout to be enabled

scenario:
  simpl: ['']
  ll: ['l1.5']
  clusters: [100]
  opts: [3H]
  planning_horizons: # investment years for myopic and perfect; or costs year for overnight
  - 2035
  sopts:
  - "3H"
  demand:
  - "DF"


electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
    StorageUnit: []  # battery, H2
    Store: [battery]
    Link: []  # H2 pipeline

  powerplants_filter: (DateOut >= 2035 or DateOut != DateOut) and (Fueltype != 'nuclear' or DateIn >= 1975)
  custom_powerplants: "replace" #  "false" use only powerplantmatching (ppm) data, "merge" combines ppm and custom powerplants, "replace" use only custom powerplants

  conventional_carriers: [nuclear, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, csp, onwind, offwind-ac, offwind-dc, hydro]

# TODO: Needs to be adjusted for Africa.
# Costs Configuration (Do not remove, needed for Sphynx documentation).
costs:
  year: 2035
  version: v0.11.0
  financial_case: "Market"
  scenario: "Moderate"
